# Git aliases
alias gs='git status'
alias gss='git status -s'
alias ga='git add'
alias gb='git branch'
alias gc='git commit -m'
alias gco='git checkout'
alias gush='/usr/bin/git push'
#alias gitlol='/usr/bin/git log --oneline --decorate --color --  graph'
alias glog='/usr/bin/git log --pretty="%h %ce \"%cd\" %n %s" --graph'
alias gdiffcache='/usr/bin/git diff --cached'
alias gdiff='/usr/bin/git diff'
alias gdiffw='/usr/bin/git diff --ignore-space-change'
